import avatar2 from '@images/avatars/avatar-2.png'
import avatar4 from '@images/avatars/avatar-4.png'
import avatar6 from '@images/avatars/avatar-6.png'
import avatar7 from '@images/avatars/avatar-7.png'
import avatar8 from '@images/avatars/avatar-8.png'

const data = [
  {
    responsiveId: '',
    id: 95,
    avatar: avatar2,
    fullName: 'TRALEX',
    post: 'Human Resources Assistant',
    email: 'Argentina',
    city: 'Puzi',
    startDate: '200000000001',
    salary: '$19586.23',
    age: '27001',
    experience: '2 Years',
    status: 1,
  },
  {
    responsiveId: '',
    id: 1,
    avatar: avatar8,
    fullName: 'GREMCOR',
    post: 'Nuclear Power Engineer',
    email: 'Peru',
    city: 'Krasnosilka',
    startDate: '200000000001',
    salary: '$96.35',
    age: '45001',
    experience: '1 Year',
    status: 2,
  },
  {
    responsiveId: '',
    id: 7,
    avatar: '',
    fullName: 'SOFTECH',
    post: 'Environmental Specialist',
    email: 'colombia',
    city: 'Lampuyang',
    startDate: '200000000001',
    salary: '$18991.67',
    age: '35001',
    experience: '9 Years',
    status: 2,
  },
  {
    responsiveId: '',
    id: 11,
    avatar: '',
    fullName: 'CORPORACION RIEL',
    post: 'Sales Representative',
    email: 'Ecuador',
    city: 'Colima',
    startDate: '200000000001',
    salary: '$19252.12',
    age: '9001',
    experience: '0 Year',
    status: 2,
  },
  {
    responsiveId: '',
    id: 3,
    avatar: avatar7,
    fullName: 'ANTAMINA',
    post: 'Operator',
    email: 'Mexico',
    city: 'Golcowa',
    startDate: '200000000001',
    salary: '$13076.28',
    age: '27001',
    experience: '6 Years',
    status: 1,
  },
  {
    responsiveId: '',
    id: 5,
    avatar: '',
    fullName: 'SAUTHER',
    post: 'Senior Cost Accountant',
    email: 'Bolivia',
    city: 'Lucan',
    startDate: '200000000001',
    salary: 10909.52,
    age: '27001',
    experience: '3 Years',
    status: 2,
  },
  {
    responsiveId: '',
    id: 6,
    avatar: '',
    fullName: 'SURGIR',
    post: 'Geologist',
    email: 'Venezuela',
    city: 'Maofan',
    startDate: '200000000001',
    salary: 17803.8,
    age: '27001',
    experience: '1 Year',
    status: 1,
  },
  {
    responsiveId: '',
    id: 4,
    avatar: avatar8,
    fullName: 'CORPORACION CORRALES',
    post: 'Cost Accountant',
    email: 'Peru',
    city: 'Paquera',
    startDate: '200000000001',
    salary: 12336.17,
    age: '27001',
    experience: '2 Years',
    status: 2,
  },
  {
    responsiveId: '',
    id: 8,
    avatar: avatar7,
    fullName: 'LORENSA',
    post: 'Senior Sales Associate',
    email: 'Peru',
    city: 'Skoghall',
    startDate: '200000000001',
    salary: 19230.13,
    age: '27001',
    experience: '5 Years',
    status: 3,
  },
  {
    responsiveId: '',
    id: 9,
    avatar: avatar2,
    fullName: 'ALICORP',
    post: 'Safety Technician',
    email: 'Peru',
    city: 'Mogilany',
    startDate: '200000000001',
    salary: 11677.32,
    age: '27001',
    experience: '9 Years',
    status: 5,
  },
  {
    responsiveId: '',
    id: 10,
    avatar: avatar7,
    fullName: 'FEMACO',
    post: 'Junior Executive',
    email: 'Peru',
    city: 'Kanuma',
    startDate: '200000000001',
    salary: 15939.52,
    age: '27001',
    experience: '3 Years',
    status: 2,
  },
  {
    responsiveId: '',
    id: 12,
    avatar: '',
    fullName: 'DISTRIBUCIONES MARFRE',
    post: 'Senior Sales Associate',
    email: 'Peru',
    city: 'Boro Utara',
    startDate: '200000000001',
    salary: 16745.47,
    age: '27001',
    experience: '2 Years',
    status: 4,
  },
  {
    responsiveId: '',
    id: 13,
    avatar: '',
    fullName: 'GREMCORP',
    post: 'Staff Accountant',
    email: 'Peru',
    city: 'Siliana',
    startDate: '200000000001',
    salary: 15488.53,
    age: '27001',
    experience: '6 Years',
    status: 4,
  },
  {
    responsiveId: '',
    id: 14,
    avatar: '',
    fullName: 'CAPRICCE INTERNACIONALE',
    post: 'Associate Professor',
    email: 'Peru',
    city: 'Brzyska',
    startDate: '200000000001',
    salary: 18442.34,
    age: '27001',
    experience: '3 Years',
    status: 2,
  },
  {
    responsiveId: '',
    id: 15,
    avatar: '',
    fullName: 'BOURTRON',
    post: 'Administrative Assistant',
    email: 'Peru',
    city: 'Bích Động',
    startDate: '200000000001',
    salary: 13304.45,
    age: '27001',
    experience: '9 Years',
    status: 5,
  },
  {
    responsiveId: '',
    id: 16,
    avatar: avatar4,
    fullName: 'TRIGRESY',
    post: 'General Manager',
    email: 'Peru',
    city: 'Gendiwu',
    startDate: '200000000001',
    salary: 11953.08,
    age: '27001',
    experience: '6 Years',
    status: 5,
  },
  {
    responsiveId: '',
    id: 17,
    avatar: '',
    fullName: 'CERRO VERDE',
    post: 'Environmental Tech',
    email: 'Peru',
    city: 'Chabařovice',
    startDate: '200000000001',
    salary: 20484.44,
    age: '27001',
    experience: '4 Years',
    status: 1,
  },
  {
    responsiveId: '',
    id: 18,
    avatar: '',
    fullName: 'Titus Hayne',
    post: 'Web Designer',
    email: 'Peru',
    city: 'Yangon',
    startDate: '200000000001',
    salary: 16871.48,
    age: '27001',
    experience: '9 Years',
    status: 1,
  },
  {
    responsiveId: '',
    id: 19,
    avatar: avatar4,
    fullName: 'Roxie Huck',
    post: 'Administrative Assistant',
    email: 'Peru',
    city: 'Polýkastro',
    startDate: '200000000001',
    salary: 19653.56,
    age: '27001',
    experience: '1 Year',
    status: 4,
  },
  {
    responsiveId: '',
    id: 20,
    avatar: avatar7,
    fullName: 'Latashia Lewtey',
    post: 'Actuary',
    email: 'Peru',
    city: 'Hougong',
    startDate: '200000000001',
    salary: 18303.87,
    age: '27001',
    experience: '5 Years',
    status: 1,
  },
  {
    responsiveId: '',
    id: 21,
    avatar: '',
    fullName: 'Natalina Tyne',
    post: 'Software Engineer',
    email: 'Peru',
    city: 'Yanguan',
    startDate: '200000000001',
    salary: 15256.4,
    age: '27001',
    experience: '0 Year',
    status: 2,
  },
  {
    responsiveId: '',
    id: 22,
    avatar: '',
    fullName: 'Faun Josefsen',
    post: 'Analog Circuit Design manager',
    email: 'Peru',
    city: 'Wengyang',
    startDate: '200000000001',
    salary: 11209.16,
    age: '27001',
    experience: '0 Year',
    status: 3,
  },
  {
    responsiveId: '',
    id: 23,
    avatar: avatar7,
    fullName: 'Rosmunda Steed',
    post: 'Assistant Media Planner',
    email: 'Peru',
    city: 'Manzanares',
    startDate: '200000000001',
    salary: 13778.34,
    age: '27001',
    experience: '1 Year',
    status: 5,
  },
  {
    responsiveId: '',
    id: 24,
    avatar: '',
    fullName: 'Scott Jiran',
    post: 'Graphic Designer',
    email: 'Peru',
    city: 'Pinglin',
    startDate: '200000000001',
    salary: 23081.71,
    age: '27001',
    experience: '3 Years',
    status: 1,
  },
  {
    responsiveId: '',
    id: 25,
    avatar: '',
    fullName: 'Carmita Medling',
    post: 'Accountant',
    email: 'Peru',
    city: 'Bourges',
    startDate: '200000000001',
    salary: 13602.24,
    age: '27001',
    experience: '7 Years',
    status: 3,
  },
  {
    responsiveId: '',
    id: 26,
    avatar: avatar2,
    fullName: 'Morgen Benes',
    post: 'Senior Sales Associate',
    email: 'Peru',
    city: 'Cà Mau',
    startDate: '200000000001',
    salary: 16969.63,
    age: '27001',
    experience: '2 Years',
    status: 4,
  },
  {
    responsiveId: '',
    id: 27,
    avatar: '',
    fullName: 'Onfroi Doughton',
    post: 'Civil Engineer',
    email: 'Peru',
    city: 'Utrecht (stad)',
    startDate: '200000000001',
    salary: 23796.62,
    age: '27001',
    experience: '8 Years',
    status: 3,
  },
  {
    responsiveId: '',
    id: 28,
    avatar: '',
    fullName: 'Kliment McGinney',
    post: 'Chief Design Engineer',
    email: 'Peru',
    city: 'Xiaocheng',
    startDate: '200000000001',
    salary: 24027.81,
    age: '27001',
    experience: '8 Years',
    status: 4,
  },
  {
    responsiveId: '',
    id: 29,
    avatar: '',
    fullName: 'Devin Bridgland',
    post: 'Tax Accountant',
    email: 'Peru',
    city: 'Baoli',
    startDate: '200000000001',
    salary: 13508.15,
    age: '27001',
    experience: '8 Years',
    status: 3,
  },
  {
    responsiveId: '',
    id: 30,
    avatar: avatar6,
    fullName: 'Gilbert McFade',
    post: 'Biostatistician',
    email: 'Peru',
    city: 'Deje',
    startDate: '200000000001',
    salary: 21632.3,
    age: '27001',
    experience: '0 Year',
    status: 2,
  },
]
const data1 = [
  {
      tipo_sistema: 1,
      nombre: '21001',
      Pais: 'Peru',
      estado: 'aceptado', //filtro
      status: 1,
  },
  {
      tipo_sistema: 2,
      nombre: 'Contabilidad',
      Pais: 'Peru',
      estado: 'no aceptado',
      status: 2,
  },
  {
      tipo_sistema: 2,
      nombre: '21001',
      Pais: 'Peru',
      estado: 'aceptado',
      status: 1,
  },
  {
      tipo_sistema: 1,
      nombre: '21001',
      Pais: 'Peru',
      estado: 'aceptado',
      status: 1,
  },
  {
      tipo_sistema: 1,
      nombre: '21001',
      Pais: 'Peru',
      estado: 'aceptado',
      status: 1,
  },
  {
      tipo_sistema: 2,
      nombre: 'Logistica',
      Pais: 'Peru',
      estado: 'aceptado',
      status: 1,
  },
  {
      tipo_sistema: 1,
      nombre: '9001',
      Pais: 'Peru',
      estado: 'aceptado',
      status: 1,
  },
  {
      tipo_sistema: 1,
      nombre: '45001',
      Pais: 'Peru',
      estado: 'no aceptado',
      status: 2,
  },
  {
      tipo_sistema: 2,
      nombre: 'RRHH',
      Pais: 'Peru',
      estado: 'aceptado',
      status: 1,
  },
  {
      tipo_sistema: 2,
      nombre: 'Finanzas',
      Pais: 'Peru',
      estado: 'no aceptado', //filtro
      status: 2, 
  },
  ]
  const data2 = [
      {
          RUC: '256781200',
          clientes: 'Gloria S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781201',
          clientes: 'alicop S.A.C',
          tipo_adquisicion: 'alquiler', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781202',
          clientes: 'gremcor S.A.C',
          tipo_adquisicion: 'alquiler', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781203',
          clientes: 'tralex S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781204',
          clientes: 'recolsa S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781205',
          clientes: 'campañaSG S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781200',
          clientes: 'gemma S.A.C',
          tipo_adquisicion: 'alquiler', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781205',
          clientes: 'concresur S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781206',
          clientes: 'territorial S.A.C',
          tipo_adquisicion: 'alquiler', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },{
          RUC: '256781207',
          clientes: 'goard S.A.C',
          tipo_adquisicion: 'alquiler', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781208',
          clientes: 'DAG contruccions S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781209',
          clientes: 'ontanario S.A.C',
          tipo_adquisicion: 'Venta', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      {
          RUC: '256781210',
          clientes: 'pachacamac S.A.C',
          tipo_adquisicion: 'alquiler', //filtro dos opciones
          fecha_adquisicion: '22/02/2024',
      },
      ]

      
      export { data, data1, data2 }
